### ISSUE TITLE
How to make the "papers" folder

### ISSUE THREAD

**Issue by edward-quinn** [jxshen311/R_citation_network_ext#1]
Hi there, 

I was wondering how you made the "papers" folder in your example of how to use the citation network code. I'm not familiar with scopus, but does it produce a bunch of text files containing the references for each article you want to include in the citation network? Thanks for your help!

**Comment by jxshen311** [comment]
Hey, thanks for reaching out! In the "example_qac_e" folder, "scopus_delta_e.csv" and "scopus_e_delta.csv" are files generated by scopus. Make sure you select at least "Doculement title" and "Include references". Scopus does not produce a bunch of text files containing the references, but the text-format references are stored as one column in the csv files. I then run the R script to extract the column and write them into separate txt files (those you see in "Papers" folder). The screenshot below shows the exact codes for this purpose. Hope this helps!
![image](https://user-images.githubusercontent.com/46509480/133820835-b2a77857-8dca-4325-b4d2-930e560b1725.png)

**Comment by jxshen311** [comment]
> Hi there,
> 
> I was wondering how you made the "papers" folder in your example of how to use the citation network code. I'm not familiar with scopus, but does it produce a bunch of text files containing the references for each article you want to include in the citation network? Thanks for your help!

Hey, thanks for reaching out! In the "example_qac_e" folder, "scopus_delta_e.csv" and "scopus_e_delta.csv" are files generated by scopus. Make sure you select at least "Doculement title" and "Include references". Scopus does not produce a bunch of text files containing the references, but the text-format references are stored as one column in the csv files. I then run the R script to extract the column and write them into separate txt files (those you see in "Papers" folder). The screenshot below shows the exact codes for this purpose. Hope this helps!
![image](https://user-images.githubusercontent.com/46509480/133821233-cfc085dc-f84b-4287-a6c1-c1f0269aa296.png)

**Comment by edward-quinn** [comment]
Well this is embarrassing...I should have read the script first 😅. I was thinking I needed the folder before running the script. Thank you for your help!!!

**Comment by jxshen311** [comment]
> Well this is embarrassing...I should have read the script first 😅. I was thinking I needed the folder before running the script. Thank you for your help!!!

No worries. Happy to take your questions~
